
#本地数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_demo_githup?userSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: system
    dbcp2:
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 18800
    #连接数据库断开
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
      #配置collect返回的页面

##需引入jar包
mybatis:
  #当mybatis的xml文件和mapper接口不在相同包下时，需要用mapperLocations属性指定xml文件的路径。
  #      *是个通配符，代表所有的文件，**代表所有目录下
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cxwmpt.demo.model
server:
  port: 8080

